## We will Start with import the Pandas and numpy library to connect the dataset to the Machine algorithm Algorithm

In [1]:
import pandas as pd
import numpy as np

#Load the CSV
df = pd.read_csv("tested.csv")

#overview
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    object
 4   Sex          418 non-null    object
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    object
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object
 11  Embarked     418 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 39.3+ KB

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

#### We can see there are many unnecessary things like:- Name,Ticket, Cabin ,PassengerId.... So we will drop it

In [2]:
df.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'], axis=1, inplace=True)

In [3]:
df

     Survived  Pclass     Sex   Age  SibSp  Parch      Fare Embarked
0           0       3    male  34.5      0      0    7.8292        Q
1           1       3  female  47.0      1      0    7.0000        S
2           0       2    male  62.0      0      0    9.6875        Q
3           0       3    male  27.0      0      0    8.6625        S
4           1       3  female  22.0      1      1   12.2875        S
..        ...     ...     ...   ...    ...    ...       ...      ...
413         0       3    male   NaN      0      0    8.0500        S
414         1       1  female  39.0      0      0  108.9000        C
415         0       3    male  38.5      0      0    7.2500        S
416         0       3    male   NaN      0      0    8.0500        S
417         0       3    male   NaN      1      1   22.3583        C

[418 rows x 8 columns]

### we Have some missing data to handel

In [4]:
#Fill missing Age with median
df['Age'].fillna(df['Age'].median(), inplace=True)

/var/folders/pb/g96r8z593g96488vwj6pg0sw0000gn/T/ipykernel_65888/3629648497.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].median(), inplace=True)

### Fill missing data in Fare and Embarked

In [5]:
df['Fare'].fillna(df['Fare'].median(), inplace=True)

## We have Embarked in a categorical column (like:-'C','Q','S') So we can't use 'median' and 'mean' so we use '.mode()' to returns the most frequent value in a column.
df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)

/var/folders/pb/g96r8z593g96488vwj6pg0sw0000gn/T/ipykernel_65888/270213021.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Fare'].fillna(df['Fare'].median(), inplace=True)
/var/folders/pb/g96r8z593g96488vwj6pg0sw0000gn/T/ipykernel_65888/270213021.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)

In [6]:
df

     Survived  Pclass     Sex   Age  SibSp  Parch      Fare Embarked
0           0       3    male  34.5      0      0    7.8292        Q
1           1       3  female  47.0      1      0    7.0000        S
2           0       2    male  62.0      0      0    9.6875        Q
3           0       3    male  27.0      0      0    8.6625        S
4           1       3  female  22.0      1      1   12.2875        S
..        ...     ...     ...   ...    ...    ...       ...      ...
413         0       3    male  27.0      0      0    8.0500        S
414         1       1  female  39.0      0      0  108.9000        C
415         0       3    male  38.5      0      0    7.2500        S
416         0       3    male  27.0      0      0    8.0500        S
417         0       3    male  27.0      1      1   22.3583        C

[418 rows x 8 columns]

#### We will use Label encoding for 'Sex' but 'Embarked' has more than two categories ('S','C','Q'),then use One-Hot Encoding to Convert it .

In [7]:
## using Sklearn for Label Encoding 
from sklearn.preprocessing import LabelEncoder
label_encoder_gender = LabelEncoder()
df['Sex'] = label_encoder_gender.fit_transform(df['Sex'])
df

     Survived  Pclass  Sex   Age  SibSp  Parch      Fare Embarked
0           0       3    1  34.5      0      0    7.8292        Q
1           1       3    0  47.0      1      0    7.0000        S
2           0       2    1  62.0      0      0    9.6875        Q
3           0       3    1  27.0      0      0    8.6625        S
4           1       3    0  22.0      1      1   12.2875        S
..        ...     ...  ...   ...    ...    ...       ...      ...
413         0       3    1  27.0      0      0    8.0500        S
414         1       1    0  39.0      0      0  108.9000        C
415         0       3    1  38.5      0      0    7.2500        S
416         0       3    1  27.0      0      0    8.0500        S
417         0       3    1  27.0      1      1   22.3583        C

[418 rows x 8 columns]

In [8]:
## using Sklearn for Ohe hot Encoding 
from sklearn.preprocessing import OneHotEncoder
onehot_Embarked = OneHotEncoder()
OH_Embarked = onehot_Embarked.fit_transform(df[['Embarked']]).toarray()
OH_Embarked

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       ...,
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [9]:
Embarked_df = pd.DataFrame(OH_Embarked,columns=onehot_Embarked.get_feature_names_out(['Embarked']))
Embarked_df

     Embarked_C  Embarked_Q  Embarked_S
0           0.0         1.0         0.0
1           0.0         0.0         1.0
2           0.0         1.0         0.0
3           0.0         0.0         1.0
4           0.0         0.0         1.0
..          ...         ...         ...
413         0.0         0.0         1.0
414         1.0         0.0         0.0
415         0.0         0.0         1.0
416         0.0         0.0         1.0
417         1.0         0.0         0.0

[418 rows x 3 columns]

### Combine one hot encoder columns with the original data

In [10]:
df=pd.concat([df.drop('Embarked',axis=1),Embarked_df],axis=1)
df.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S
0,0,3,1,34.5,0,0,7.8292,0.0,1.0,0.0
1,1,3,0,47.0,1,0,7.0000,0.0,0.0,1.0
2,0,2,1,62.0,0,0,9.6875,0.0,1.0,0.0
3,0,3,1,27.0,0,0,8.6625,0.0,0.0,1.0
4,1,3,0,22.0,1,1,12.2875,0.0,0.0,1.0

## Now we will Split Dependent and Independent variable

In [11]:
X = df.drop('Survived',axis=1)
y = df['Survived']

In [12]:
X

,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S
0,3,1,34.5,0,0,7.8292,0.0,1.0,0.0
1,3,0,47.0,1,0,7.0000,0.0,0.0,1.0
2,2,1,62.0,0,0,9.6875,0.0,1.0,0.0
3,3,1,27.0,0,0,8.6625,0.0,0.0,1.0
4,3,0,22.0,1,1,12.2875,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...
413,3,1,27.0,0,0,8.0500,0.0,0.0,1.0
414,1,0,39.0,0,0,108.9000,1.0,0.0,0.0
415,3,1,38.5,0,0,7.2500,0.0,0.0,1.0
416,3,1,27.0,0,0,8.0500,0.0,0.0,1.0
417,3,1,27.0,1,1,22.3583,1.0,0.0,0.0

In [13]:
y

0      0
1      1
2      0
3      0
4      1
      ..
413    0
414    1
415    0
416    0
417    0
Name: Survived, Length: 418, dtype: int64

In [14]:
df.shape

(418, 10)

## Spliting The Data into Test set and Training Set

In [31]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25, random_state=42)

In [32]:
X_train

,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S
132,3,0,27.0,0,4,25.4667,0.0,0.0,1.0
60,3,1,17.0,0,0,7.8958,0.0,0.0,1.0
198,2,1,23.0,0,0,10.5000,0.0,0.0,1.0
332,3,1,27.0,0,0,7.2250,1.0,0.0,0.0
63,3,0,22.0,0,0,7.7250,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...
71,3,1,21.0,0,0,7.8958,0.0,0.0,1.0
106,3,1,21.0,0,0,7.8208,0.0,1.0,0.0
270,1,1,46.0,0,0,75.2417,1.0,0.0,0.0
348,2,1,24.0,0,0,13.5000,0.0,0.0,1.0
102,3,1,27.0,0,0,7.7500,0.0,1.0,0.0

In [17]:
X_test

,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S
360,3,1,14.5,8,2,69.5500,0.0,0.0,1.0
170,3,1,27.0,0,0,7.5500,0.0,0.0,1.0
224,1,0,53.0,0,0,27.4458,1.0,0.0,0.0
358,3,1,27.0,0,0,7.7500,0.0,1.0,0.0
309,3,0,45.0,1,0,14.1083,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...
390,1,1,23.0,0,0,93.5000,0.0,0.0,1.0
274,3,1,27.0,0,0,7.2250,1.0,0.0,0.0
217,1,1,57.0,1,1,164.8667,0.0,0.0,1.0
397,1,0,48.0,1,1,79.2000,1.0,0.0,0.0
325,3,1,23.0,0,0,7.0500,0.0,0.0,1.0

In [18]:
y_train

208    1
56     0
8      1
315    1
155    0
      ..
323    0
192    0
117    1
47     0
172    0
Name: Survived, Length: 313, dtype: int64

In [19]:
y_test

360    0
170    0
224    1
358    0
309    1
      ..
390    0
274    0
217    0
397    1
325    0
Name: Survived, Length: 105, dtype: int64

## Featuring Scaling

In [20]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [21]:
X_train

array([[-1.55652696, -1.4074631 ,  0.24849053, ...,  1.81319366,
        -0.36050506, -1.36804957],
       [ 0.84343825,  0.7104982 ,  0.40244143, ..., -0.55151307,
        -0.36050506,  0.73096766],
       [ 0.84343825, -1.4074631 , -0.90614123, ...,  1.81319366,
        -0.36050506, -1.36804957],
       ...,
       [ 0.84343825, -1.4074631 , -2.2147239 , ..., -0.55151307,
        -0.36050506,  0.73096766],
       [ 0.84343825,  0.7104982 , -0.21336218, ..., -0.55151307,
         2.77388616, -1.36804957],
       [ 0.84343825,  0.7104982 , -0.52126398, ..., -0.55151307,
        -0.36050506,  0.73096766]])

In [22]:
X_test

array([[ 0.84343825,  0.7104982 , -1.17555531, 10.66141028,  1.5403959 ,
         0.69595086, -0.55151307, -0.36050506,  0.73096766],
       [ 0.84343825,  0.7104982 , -0.21336218, -0.56018339, -0.37667733,
        -0.46169998, -0.55151307, -0.36050506,  0.73096766],
       [-1.55652696, -1.4074631 ,  1.78799954, -0.56018339, -0.37667733,
        -0.09020983,  1.81319366, -0.36050506, -1.36804957],
       [ 0.84343825,  0.7104982 , -0.21336218, -0.56018339, -0.37667733,
        -0.45796562, -0.55151307,  2.77388616, -1.36804957],
       [ 0.84343825, -1.4074631 ,  1.17219594,  0.84251582, -0.37667733,
        -0.33924479, -0.55151307, -0.36050506,  0.73096766],
       [-1.55652696,  0.7104982 ,  1.94195044,  0.84251582,  0.58185929,
         1.14314017, -0.55151307, -0.36050506,  0.73096766],
       [-1.55652696, -1.4074631 , -0.52126398, -0.56018339,  0.58185929,
         0.95004215,  1.81319366, -0.36050506, -1.36804957],
       [ 0.84343825,  0.7104982 , -0.21336218, -0.56018339, -0.37667733,
        -0.45524327, -0.55151307, -0.36050506,  0.73096766],
       [ 0.84343825,  0.7104982 , -1.59892029, -0.56018339,  0.58185929,
        -0.54346747, -0.55151307, -0.36050506,  0.73096766],
       [ 0.84343825,  0.7104982 , -0.67521488, -0.56018339, -0.37667733,
        -0.45602002, -0.55151307, -0.36050506,  0.73096766],
       [-0.35654435, -1.4074631 ,  0.09453963, -0.56018339, -0.37667733,
        -0.21056443, -0.55151307, -0.36050506,  0.73096766],
       [-1.55652696, -1.4074631 ,  0.47941688, -0.56018339, -0.37667733,
         4.29633832,  1.81319366, -0.36050506, -1.36804957],
       [-0.35654435,  0.7104982 , -0.52126398,  0.84251582, -0.37667733,
        -0.40661821, -0.55151307, -0.36050506,  0.73096766],
       [-0.35654435,  0.7104982 , -0.52126398, -0.56018339, -0.37667733,
        -0.40661821, -0.55151307, -0.36050506,  0.73096766],
       [-0.35654435,  0.7104982 , -0.90614123, -0.56018339, -0.37667733,
         0.76970442, -0.55151307, -0.36050506,  0.73096766],
       [ 0.84343825,  0.7104982 , -0.21336218, -0.56018339, -0.37667733,
        -0.45236408, -0.55151307, -0.36050506,  0.73096766],
       [ 0.84343825, -1.4074631 , -0.59823943,  2.24521503, -0.37667733,
        -0.44092762, -0.55151307, -0.36050506,  0.73096766],
       [-0.35654435,  0.7104982 ,  0.86429413, -0.56018339, -0.37667733,
        -0.35993874, -0.55151307, -0.36050506,  0.73096766],
       [-1.55652696, -1.4074631 , -0.52126398,  0.84251582, -0.37667733,
         0.93339438, -0.55151307, -0.36050506,  0.73096766],
       [ 0.84343825, -1.4074631 , -0.21336218, 10.66141028,  1.5403959 ,
         0.69595086, -0.55151307, -0.36050506,  0.73096766],
       [-0.35654435,  0.7104982 , -0.29033763, -0.56018339, -0.37667733,
        -0.35993874, -0.55151307, -0.36050506,  0.73096766],
       [ 0.84343825, -1.4074631 , -0.67521488, -0.56018339, -0.37667733,
        -0.44092762, -0.55151307, -0.36050506,  0.73096766],
       [-0.35654435,  0.7104982 , -0.21336218, -0.56018339, -0.37667733,
        -0.36227271, -0.55151307, -0.36050506,  0.73096766],
       [-0.35654435,  0.7104982 , -0.21336218, -0.56018339, -0.37667733,
        -0.31178046,  1.81319366, -0.36050506, -1.36804957],
       [ 0.84343825,  0.7104982 ,  0.09453963,  3.64791424, -0.37667733,
        -0.2665798 , -0.55151307, -0.36050506,  0.73096766],
       [-1.55652696,  0.7104982 , -0.44428853,  0.84251582, -0.37667733,
         0.93339438, -0.55151307, -0.36050506,  0.73096766],
       [ 0.84343825, -1.4074631 , -0.21336218, -0.56018339, -0.37667733,
        -0.4511971 , -0.55151307, -0.36050506,  0.73096766],
       [ 0.84343825,  0.7104982 ,  0.2100028 , -0.56018339, -0.37667733,
        -0.42528999, -0.55151307, -0.36050506,  0.73096766],
       [-1.55652696,  0.7104982 ,  1.94195044, -0.56018339, -0.37667733,
         0.33091741, -0.55151307, -0.36050506,  0.73096766],
       [ 0.84343825,  0.7104982 , -0.90614123, -0.56018339, -0.37667733,
        -0.44092762, -0.55151307, -0.36050506,  0.73096766],
       [-1.55652696, -1.4074631 ,  1.17219594, -0.56018339, -0.37667733,
         4.29633832,  1.81319366, -0.36050506, -1.36804957],
       [-1.55652696, -1.4074631 ,  1.40312229,  0.84251582, -0.37667733,
         1.38447303,  1.81319366, -0.36050506, -1.36804957],
       [ 0.84343825, -1.4074631 , -0.59823943,  0.84251582, -0.37667733,
        -0.34313413, -0.55151307, -0.36050506,  0.73096766],
       [-0.35654435, -1.4074631 , -0.44428853,  0.84251582, -0.37667733,
        -0.08507508,  1.81319366, -0.36050506, -1.36804957],
       [ 0.84343825, -1.4074631 , -0.21336218, -0.56018339, -0.37667733,
        -0.45796562, -0.55151307,  2.77388616, -1.36804957],
       [ 0.84343825,  0.7104982 , -0.21336218, -0.56018339, -0.37667733,
        -0.46768989,  1.81319366, -0.36050506, -1.36804957],
       [-0.35654435,  0.7104982 ,  1.01824503, -0.56018339,  0.58185929,
        -0.21056443, -0.55151307, -0.36050506,  0.73096766],
       [-1.55652696, -1.4074631 ,  0.24849053, -0.56018339, -0.37667733,
         2.22703745, -0.55151307, -0.36050506,  0.73096766],
       [-1.55652696, -1.4074631 ,  0.40244143, -0.56018339, -0.37667733,
         3.34641112,  1.81319366, -0.36050506, -1.36804957],
       [ 0.84343825, -1.4074631 , -0.21336218,  0.84251582, -0.37667733,
        -0.33278622,  1.81319366, -0.36050506, -1.36804957],
       [-0.35654435, -1.4074631 , -0.44428853,  0.84251582,  0.58185929,
         0.08826259,  1.81319366, -0.36050506, -1.36804957],
       [-0.35654435,  0.7104982 ,  0.01756417, -0.56018339, -0.37667733,
        -0.35993874, -0.55151307, -0.36050506,  0.73096766],
       [ 0.84343825, -1.4074631 , -0.21336218, -0.56018339, -0.37667733,
        -0.45796562, -0.55151307,  2.77388616, -1.36804957],
       [ 0.84343825, -1.4074631 , -0.59823943, -0.56018339, -0.37667733,
         0.1383646 , -0.55151307, -0.36050506,  0.73096766],
       [-0.35654435,  0.7104982 , -0.21336218, -0.56018339, -0.37667733,
        -0.32173999,  1.81319366, -0.36050506, -1.36804957],
       [ 0.84343825, -1.4074631 ,  0.47941688, -0.56018339,  1.5403959 ,
        -0.37518798, -0.55151307, -0.36050506,  0.73096766],
       [ 0.84343825,  0.7104982 , -0.21336218, -0.56018339, -0.37667733,
        -0.45236408, -0.55151307, -0.36050506,  0.73096766],
       [ 0.84343825,  0.7104982 , -0.67521488, -0.56018339, -0.37667733,
        -0.45796562, -0.55151307,  2.77388616, -1.36804957],
       [ 0.84343825,  0.7104982 , -0.98311668, -0.56018339, -0.37667733,
        -0.45524327, -0.55151307, -0.36050506,  0.73096766],
       [-0.35654435,  0.7104982 , -0.67521488, -0.56018339, -0.37667733,
        -0.35993874, -0.55151307, -0.36050506,  0.73096766],
       [ 0.84343825,  0.7104982 , -0.21336218,  0.84251582,  0.58185929,
        -0.18520255,  1.81319366, -0.36050506, -1.36804957],
       [ 0.84343825, -1.4074631 ,  0.01756417, -0.56018339, -0.37667733,
        -0.46022117, -0.55151307,  2.77388616, -1.36804957],
       [ 0.84343825, -1.4074631 ,  1.32614684,  0.84251582, -0.37667733,
        -0.47196946, -0.55151307, -0.36050506,  0.73096766],
       [ 0.84343825,  0.7104982 , -0.21336218, -0.56018339, -0.37667733,
        -0.46123318, -0.55151307, -0.36050506,  0.73096766],
       [-1.55652696,  0.7104982 ,  0.94126958, -0.56018339, -0.37667733,
        -0.10693601, -0.55151307, -0.36050506,  0.73096766],
       [-1.55652696, -1.4074631 , -0.29033763,  0.84251582, -0.37667733,
         1.95124021,  1.81319366, -0.36050506, -1.36804957],
       [ 0.84343825,  0.7104982 , -0.21336218, -0.56018339, -0.37667733,
        -0.45796562, -0.55151307,  2.77388616, -1.36804957],
       [ 0.84343825, -1.4074631 , -0.21336218, -0.56018339,  3.45746912,
        -0.12716316, -0.55151307, -0.36050506,  0.73096766],
       [ 0.84343825,  0.7104982 , -0.75219033, -0.56018339, -0.37667733,
        -0.45602002, -0.55151307, -0.36050506,  0.73096766],
       [ 0.84343825,  0.7104982 , -0.21336218, -0.56018339, -0.37667733,
        -0.46730152, -0.55151307, -0.36050506,  0.73096766],
       [-0.35654435,  0.7104982 ,  0.32546598,  0.84251582, -0.37667733,
        -0.1172055 , -0.55151307, -0.36050506,  0.73096766],
       [-0.35654435, -1.4074631 , -0.21336218, -0.56018339, -0.37667733,
        -0.21056443, -0.55151307, -0.36050506,  0.73096766],
       [-1.55652696, -1.4074631 ,  2.6347295 , -0.56018339,  1.5403959 ,
         0.95004215,  1.81319366, -0.36050506, -1.36804957],
       [ 0.84343825,  0.7104982 , -0.21336218, -0.56018339, -0.37667733,
        -0.45796562, -0.55151307,  2.77388616, -1.36804957],
       [ 0.84343825,  0.7104982 ,  1.01824503, -0.56018339, -0.37667733,
        -0.45524327, -0.55151307, -0.36050506,  0.73096766],
       [-0.35654435, -1.4074631 , -0.67521488, -0.56018339,  0.58185929,
        -0.21056443, -0.55151307, -0.36050506,  0.73096766],
       [ 0.84343825, -1.4074631 ,  0.47941688, -0.56018339,  1.5403959 ,
        -0.30579055, -0.55151307, -0.36050506,  0.73096766],
       [-0.35654435, -1.4074631 , -0.75219033,  2.24521503,  0.58185929,
        -0.17322086, -0.55151307, -0.36050506,  0.73096766],
       [-1.55652696, -1.4074631 , -0.59823943, -0.56018339,  0.58185929,
         0.55459049,  1.81319366, -0.36050506, -1.36804957],
       [ 0.84343825,  0.7104982 , -0.36731308, -0.56018339, -0.37667733,
        -0.45469806, -0.55151307, -0.36050506,  0.73096766],
       [ 0.84343825,  0.7104982 , -0.44428853, -0.56018339, -0.37667733,
        -0.45602002, -0.55151307, -0.36050506,  0.73096766],
       [ 0.84343825, -1.4074631 , -0.59823943,  0.84251582,  0.58185929,
        -0.37324238, -0.55151307, -0.36050506,  0.73096766],
       [-0.35654435, -1.4074631 ,  0.01756417,  0.84251582, -0.37667733,
        -0.34391274,  1.81319366, -0.36050506, -1.36804957],
       [-1.55652696, -1.4074631 ,  0.09453963, -0.56018339, -0.37667733,
         1.90868347,  1.81319366, -0.36050506, -1.36804957],
       [-1.55652696, -1.4074631 ,  0.40244143,  0.84251582, -0.37667733,
         0.47562376,  1.81319366, -0.36050506, -1.36804957],
       [-0.35654435,  0.7104982 , -1.21404304, -0.56018339, -0.37667733,
         0.61099422, -0.55151307, -0.36050506,  0.73096766],
       [ 0.84343825,  0.7104982 , -1.21404304, -0.56018339, -0.37667733,
        -0.43042473, -0.55151307, -0.36050506,  0.73096766],
       [-0.35654435, -1.4074631 , -0.75219033, -0.56018339, -0.37667733,
         0.08351622, -0.55151307, -0.36050506,  0.73096766],
       [ 0.84343825,  0.7104982 , -0.59823943, -0.56018339, -0.37667733,
        -0.46776831,  1.81319366, -0.36050506, -1.36804957],
       [-1.55652696, -1.4074631 ,  1.01824503,  0.84251582, -0.37667733,
         0.43252368,  1.81319366, -0.36050506, -1.36804957],
       [-0.35654435,  0.7104982 , -0.29033763,  0.84251582,  0.58185929,
        -0.06119013, -0.55151307, -0.36050506,  0.73096766],
       [-1.55652696, -1.4074631 , -0.21336218, -0.56018339, -0.37667733,
        -0.01108812, -0.55151307, -0.36050506,  0.73096766],
       [-1.55652696,  0.7104982 ,  0.09453963, -0.56018339, -0.37667733,
        -0.06982583,  1.81319366, -0.36050506, -1.36804957],
       [-0.35654435,  0.7104982 , -0.05941128,  0.84251582, -0.37667733,
        -0.1172055 , -0.55151307, -0.36050506,  0.73096766],
       [-1.55652696,  0.7104982 ,  1.94195044,  0.84251582, -0.37667733,
         0.50643221,  1.81319366, -0.36050506, -1.36804957],
       [-1.55652696,  0.7104982 ,  0.01756417,  0.84251582,  1.5403959 ,
         2.22703745, -0.55151307, -0.36050506,  0.73096766],
       [-1.55652696,  0.7104982 ,  2.40380315,  0.84251582,  2.49893251,
         4.29633832,  1.81319366, -0.36050506, -1.36804957],
       [-1.55652696, -1.4074631 ,  1.32614684,  0.84251582, -0.37667733,
         0.53957464, -0.55151307, -0.36050506,  0.73096766],
       [ 0.84343825, -1.4074631 , -2.13774845,  0.84251582,  0.58185929,
        -0.22526847, -0.55151307, -0.36050506,  0.73096766],
       [ 0.84343825,  0.7104982 , -0.21336218, -0.56018339, -0.37667733,
        -0.45796562, -0.55151307,  2.77388616, -1.36804957],
       [ 0.84343825, -1.4074631 , -0.21336218, -0.56018339, -0.37667733,
        -0.45236408, -0.55151307, -0.36050506,  0.73096766],
       [ 0.84343825, -1.4074631 , -0.86765351, -0.56018339, -0.37667733,
        -0.46667974, -0.55151307,  2.77388616, -1.36804957],
       [-1.55652696,  0.7104982 ,  0.2100028 , -0.56018339, -0.37667733,
         3.34641112,  1.81319366, -0.36050506, -1.36804957],
       [-1.55652696,  0.7104982 , -1.29101849,  2.24521503,  1.5403959 ,
         4.29633832,  1.81319366, -0.36050506, -1.36804957],
       [ 0.84343825,  0.7104982 , -1.52194484,  5.05061345,  0.58185929,
        -0.05885616, -0.55151307,  2.77388616, -1.36804957],
       [-0.35654435, -1.4074631 , -2.22088193,  0.84251582,  1.5403959 ,
        -0.08452987, -0.55151307, -0.36050506,  0.73096766],
       [-1.55652696, -1.4074631 ,  1.17219594, -0.56018339,  0.58185929,
         0.58034075,  1.81319366, -0.36050506, -1.36804957],
       [-0.35654435, -1.4074631 , -0.59823943, -0.56018339, -0.37667733,
        -0.21056443, -0.55151307, -0.36050506,  0.73096766],
       [ 0.84343825,  0.7104982 , -1.29101849,  5.05061345,  1.5403959 ,
        -0.01661124, -0.55151307, -0.36050506,  0.73096766],
       [-1.55652696,  0.7104982 ,  0.86429413,  0.84251582, -0.37667733,
         0.36569361, -0.55151307, -0.36050506,  0.73096766],
       [-1.55652696,  0.7104982 , -0.52126398, -0.56018339, -0.37667733,
         1.14314017, -0.55151307, -0.36050506,  0.73096766],
       [ 0.84343825,  0.7104982 , -0.21336218, -0.56018339, -0.37667733,
        -0.46776831,  1.81319366, -0.36050506, -1.36804957],
       [-1.55652696,  0.7104982 ,  2.09590134,  0.84251582,  0.58185929,
         2.47568404, -0.55151307, -0.36050506,  0.73096766],
       [-1.55652696, -1.4074631 ,  1.40312229,  0.84251582,  0.58185929,
         0.87613361,  1.81319366, -0.36050506, -1.36804957],
       [ 0.84343825,  0.7104982 , -0.52126398, -0.56018339, -0.37667733,
        -0.47103587, -0.55151307, -0.36050506,  0.73096766]])

## Using LogisticRegression , RandomForestClassifier , DecisionTreeClassifier

In [23]:
df

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S
0,0,3,1,34.5,0,0,7.8292,0.0,1.0,0.0
1,1,3,0,47.0,1,0,7.0000,0.0,0.0,1.0
2,0,2,1,62.0,0,0,9.6875,0.0,1.0,0.0
3,0,3,1,27.0,0,0,8.6625,0.0,0.0,1.0
4,1,3,0,22.0,1,1,12.2875,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...
413,0,3,1,27.0,0,0,8.0500,0.0,0.0,1.0
414,1,1,0,39.0,0,0,108.9000,1.0,0.0,0.0
415,0,3,1,38.5,0,0,7.2500,0.0,0.0,1.0
416,0,3,1,27.0,0,0,8.0500,0.0,0.0,1.0
417,0,3,1,27.0,1,1,22.3583,1.0,0.0,0.0

## LoogisticRegression

In [24]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression(random_state = 0)
LR.fit(X_train, y_train)

LogisticRegression(random_state=0)

#### Predicting the test set

In [25]:
y_pred = LR.predict(X_test)
y_test_np = y_test.values
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test_np.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]]

### Accuracy and confusion matrix of LogisticRegression

In [26]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[58  0]
 [ 0 47]]

1.0

## Random Forest

In [27]:
from sklearn.ensemble import RandomForestClassifier
RF = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
RF.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

### Accuracy and confusion matrix of RandomForestClassifier

In [28]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = RF.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[58  0]
 [ 0 47]]

1.0

## DecisionTreeClassifier

In [29]:
from sklearn.tree import DecisionTreeClassifier
DT = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
DT.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

### Accuracy and confusion matrix of DecisionTreeClassifier

In [30]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = DT.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[58  0]
 [ 0 47]]

1.0

In [33]:
import numpy as np

# Create input for one new passenger
new_passenger = pd.DataFrame([{
    'Pclass': 3,
    'Age': 22,
    'SibSp': 1,
    'Parch': 0,
    'Fare': 7.25,
    'Sex': 1,
    'Embarked_C': 0 ,
    'Embarked_Q': 0,
    'Embarked_S': 1
}])

# Ensure the columns are in the same order as the training data
new_passenger = new_passenger[sc.feature_names_in_]  # Align columns with scaler's feature names

# Scale the new input
new_passenger_scaled = sc.transform(new_passenger)

# Predict
prediction = LR.predict(new_passenger_scaled)
print("Predicted Survival:", "Survived" if prediction[0] == 1 else "Did Not Survive")

Predicted Survival: Did Not Survive

## - Hence we can see that we predicted the dataset with 100 percent in this situation.